tasks:
  - path: ~/.gitconfig
    source: gitconfig
    mode: link
  - path: ~/.gitignore_global
    source: gitignore_global
    mode: link
  - path: ~/.vimrc
    source: vimrc
    mode: link
  - path: ~/.bashrc
    source: bashrc
    mode: link

  - path: ~/.ssh
    mode: mkdir
    chmod: 700
  - path: ~/.ssh/config
    source: ssh_config
    mode: link